version: "3"
services:
    insert:
        image: pachecowillians/get-all:latest
        ports:
            - "3331:3000"
        env_file:
            - ../.env
        deploy:
            replicas: 2
            placement:
                constraints: [node.role==worker]
