version: "3"
services:
    insert:
        restart: on-failure
        image: pachecowillians/insert
        ports:
            - "3330:3000"
        environment:
            HOST: 192.168.99.102
        deploy:
            replicas: 2
            placement:
                constraints: [node.role==worker]
