version: "3"
services:
    insert:
        restart: on-failure
        build: ../insert/
        container_name: insert
        ports:
            - "3330:3000"
        deploy:
            replicas: 2
            placement:
                constraints: [node.role==worker]
