version: "3"
services:
    insert:
        restart: on-failure
        image: pachecowillians/insert:latest
        ports:
            - "3330:3000"
        env_file:
            - ../.env
        deploy:
            replicas: 2
            placement:
                constraints: [node.role==worker]
